version: '3.7'
services:
  reverse-proxy:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443     
  api:
    build: 
        context: ./
        dockerfile: api/Dockerfile
    restart: unless-stopped
    ports :
      - 6000:5000
     
  home:
    build:
        context: ./
        dockerfile: home/Dockerfile
    restart: unless-stopped
    ports :
       - 5000:5000
     
  

   
  
      
      