import Head from 'next/head'
import Home from "@/pages/home";

export default function Index() {
  return (
    <>
      <Head>
        <title>MPB</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Home />

      </main>
    </>
  )
}
